CLASS zcl_labb_18_animal DEFINITION PUBLIC CREATE PUBLIC.
  PUBLIC SECTION.
  METHODS: walk RETURNING VALUE(rv_action) TYPE string.
  PROTECTED SECTION.
  PRIVATE SECTION.
ENDCLASS.

CLASS zcl_labb_18_animal IMPLEMENTATION.
  METHOD walk.
    rv_action = 'The ANIMAL walk'.
  ENDMETHOD.
ENDCLASS.
