CLASS zcl_labb_12_linux DEFINITION INHERITING FROM zcl_labb_11_system PUBLIC CREATE PUBLIC.
  PUBLIC SECTION.
  PROTECTED SECTION.
  PRIVATE SECTION.
ENDCLASS.

CLASS zcl_labb_12_linux IMPLEMENTATION.
ENDCLASS.
