CLASS zcl_labb_23_company DEFINITION PUBLIC FINAL CREATE PUBLIC GLOBAL FRIENDS zcl_labb_24_partner.
  PUBLIC SECTION.
  PROTECTED SECTION.
  PRIVATE SECTION.
  DATA: lv_capital TYPE f VALUE '7000.45'.
ENDCLASS.

CLASS zcl_labb_23_company IMPLEMENTATION.
ENDCLASS.
