CLASS zcl_labb_19_lion DEFINITION INHERITING FROM zcl_labb_18_animal PUBLIC FINAL CREATE PUBLIC.
  PUBLIC SECTION.
  METHODS: walk REDEFINITION.
  PROTECTED SECTION.
  PRIVATE SECTION.
ENDCLASS.

CLASS zcl_labb_19_lion IMPLEMENTATION.
  METHOD walk.
    rv_action = 'The LION walks'.
  ENDMETHOD.
ENDCLASS.
